### ISSUE TITLE
no desafio a validação não especifica que seria só por ano

### ISSUE THREAD

**Issue by gabrielsfarias** [gustavomolina17/Blue-Edtech-C008-M01-LAP#1]
1. ##### Como eu faria se tivesse que validar uma data de nascimento completa `dd/mm/yyyy`, com zeros à esquerda e barras?
2. ##### Existe diferença pra meses com dias diferentes, como fevereiro e meses com 30 ou 31 dias?

**Comment by gustavomolina17** [comment]
1. Existem diferentes maneiras. Mando aqui uma sugestão dentre as possíveis: 
https://pt.stackoverflow.com/questions/298042/validar-campo-data-de-nascimento-com-javascript

2. Sim, existe ao fazer a validação você deve levar todas as hipóteses em consideração: meses com 30 ou 31 dias, fevereiro e ano bissexto.
